modLoader="javafml"
loaderVersion="${forge_loader_range}"
license="CC BY-NC-ND 4.0"
showAsResourcePack=false
issueTrackerURL="https://github.com/tristankechlo/LivingThings/issues"

[[mods]]
modId="livingthings"
version="${version}"
displayName="Living Things"
displayURL="https://github.com/tristankechlo/LivingThings"
logoFile="banner.png"
authors="Buecher_wurm"
description='''adds various new mobs to Minecraft'''

[[dependencies.livingthings]]
modId="forge"
mandatory=true
versionRange="${forge_loader_range}"
ordering="NONE"
side="BOTH"

[[dependencies.livingthings]]
modId="minecraft"
mandatory=true
versionRange="${version_range}"
ordering="NONE"
side="BOTH"