modLoader="javafml"
loaderVersion="[45,)"
license="CC BY-NC-ND 4.0"
showAsResourcePack=false
issueTrackerURL="https://github.com/tristankechlo/LivingThings/issues"

[[mods]]
modId="livingthings"
version="${version}"
displayName="Living Things"
displayURL="https://github.com/tristankechlo/LivingThings"
logoFile="banner.png"
authors="Buecher_wurm"
description='''adds various new mobs to Minecraft'''

[[dependencies.livingthings]]
modId="forge"
mandatory=true
versionRange="[45,)"
ordering="NONE"
side="BOTH"

[[dependencies.livingthings]]
modId="minecraft"
mandatory=true
versionRange="[1.19.4,1.20)"
ordering="NONE"
side="BOTH"