modLoader="javafml" #mandatory
loaderVersion="[33,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
showAsResourcePack=false

#issueTrackerURL="http://my.issue.tracker/" #optional
[[mods]] #mandatory
	modId="livingthings" #mandatory
	version="1.16.2 - 1.1.2" #mandatory
	displayName="Living Things" #mandatory
	#updateJSONURL="http://myurl.me/" #optional
	#displayURL="http://example.com/" #optional
	#logoFile="livingthings.png" #optional
	#credits="Thanks for this example mod goes to Java" #optional
	authors="Buecher_wurm" #optional
	# The description text for the mod (multi line!) (#mandatory)
	description='''adds various new mobs to Minecraft'''

# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.livingthings]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[33,)" #mandatory
    ordering="NONE"
    side="BOTH"
	
# Here's another dependency
[[dependencies.livingthings]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.2]"
    ordering="NONE"
    side="BOTH"
